import { PlaceholderAgent } from './placeholder-agents';
import { voiceConfigs } from './voices';

export const additionalAgents: PlaceholderAgent[] = [
  {
    id: "11",
    name: "Barton Springs Pool",
    slug: "barton-springs-pool",
    description: "Historic natural spring-fed pool in the heart of Austin",
    image_url: "https://placehold.co/400x400?text=Barton+Springs",
    interests: ["Swimming", "Nature", "History"],
    likes: ["Cool waters", "Year-round swimming", "Natural habitat"],
    dislikes: ["Pollution", "Overcrowding", "Drought"],
    fun_facts: [
      "Maintains 68-70 degree temperature year-round",
      "Home to endangered Barton Springs Salamander",
      "Has been operating since the 1920s"
    ],
    location: "Zilker Park",
    coordinates: "30.2642° N, 97.7714° W",
    twitter_handle: "@BartonSprings",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    category: "parksAndNature",
    latitude: 30.2642,
    longitude: -97.7714,
    personality: "A refreshing and invigorating presence that speaks with crystal clarity about nature, conservation, and the joy of swimming.",
    data_sources: [],
    user_id: "public"
  },
  {
    id: "12",
    name: "Austin City Limits",
    slug: "austin-city-limits",
    description: "Iconic music venue and television show",
    image_url: "https://placehold.co/400x400?text=ACL",
    interests: ["Music", "Television", "Live Performance"],
    likes: ["Live music", "Cultural preservation", "Musical diversity"],
    dislikes: ["Poor acoustics", "Technical difficulties"],
    fun_facts: [
      "Longest-running music program in television history",
      "Moved to Moody Theater in 2011",
      "Has hosted thousands of legendary performances"
    ],
    location: "ACL Live at The Moody Theater",
    coordinates: "30.2658° N, 97.7474° W",
    twitter_handle: "@acltv",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    category: "historicSites",
    latitude: 30.2658,
    longitude: -97.7474,
    personality: "A sophisticated and culturally rich presence that speaks with authority about music history and live performance.",
    data_sources: [],
    user_id: "public"
  },
  {
    id: "13",
    name: "South Congress Bridge",
    slug: "south-congress-bridge",
    description: "Historic bridge and bat-watching destination",
    image_url: "https://placehold.co/400x400?text=Congress+Bridge",
    interests: ["Architecture", "Wildlife", "Urban Planning"],
    likes: ["Sunset views", "Bat colonies", "Pedestrian traffic"],
    dislikes: ["Structural damage", "Noise pollution"],
    fun_facts: [
      "Home to largest urban bat colony in North America",
      "Built in 1910",
      "Renovated in 1980 to accommodate bat habitat"
    ],
    location: "Congress Avenue",
    coordinates: "30.2616° N, 97.7450° W",
    twitter_handle: "",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    category: "historicSites",
    latitude: 30.2616,
    longitude: -97.7450,
    personality: "A sturdy and reliable presence that connects Austin's past and present, speaking with pride about its role in the city's infrastructure and wildlife conservation.",
    data_sources: [],
    user_id: "public"
  },
  {
    id: "14",
    name: "Hope Outdoor Gallery",
    slug: "hope-outdoor-gallery",
    description: "Community art park and graffiti gallery",
    image_url: "https://placehold.co/400x400?text=Hope+Gallery",
    interests: ["Street Art", "Community", "Urban Culture"],
    likes: ["Creative expression", "Community events", "Art education"],
    dislikes: ["Vandalism", "Littering"],
    fun_facts: [
      "Originally a failed condo development",
      "Relocated to Carson Creek Ranch",
      "Features rotating murals by local artists"
    ],
    location: "Carson Creek Ranch",
    coordinates: "30.2472° N, 97.7145° W",
    twitter_handle: "@HOGATx",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    category: "publicArt",
    latitude: 30.2472,
    longitude: -97.7145,
    personality: "A vibrant and evolving canvas that speaks with passion about artistic expression and community engagement.",
    data_sources: [],
    user_id: "public"
  },
  {
    id: "15",
    name: "Waterloo Records",
    slug: "waterloo-records",
    description: "Iconic independent music store",
    image_url: "https://placehold.co/400x400?text=Waterloo",
    interests: ["Music", "Vinyl Records", "Local Culture"],
    likes: ["Music discovery", "Local artists", "Record Store Day"],
    dislikes: ["Digital streaming", "Corporate chains"],
    fun_facts: [
      "Operating since 1982",
      "Named after Austin's original name",
      "Hosts regular in-store performances"
    ],
    location: "North Lamar Boulevard",
    coordinates: "30.2705° N, 97.7534° W",
    twitter_handle: "@WaterlooRecords",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    category: "businesses",
    latitude: 30.2705,
    longitude: -97.7534,
    personality: "A knowledgeable and passionate curator of music culture, speaking with enthusiasm about vinyl records and Austin's music scene.",
    data_sources: [],
    user_id: "public"
  },
  {
    id: "16",
    name: "Mount Bonnell",
    slug: "mount-bonnell",
    description: "Highest point in Austin with panoramic views",
    image_url: "https://placehold.co/400x400?text=Mt+Bonnell",
    interests: ["Hiking", "Photography", "Nature"],
    likes: ["Sunset views", "Outdoor recreation", "City vistas"],
    dislikes: ["Erosion", "Overcrowding"],
    fun_facts: [
      "Named after George Bonnell in 1830s",
      "Elevation of 775 feet",
      "Popular proposal spot"
    ],
    location: "Mount Bonnell Road",
    coordinates: "30.3210° N, 97.7736° W",
    twitter_handle: "",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    category: "parksAndNature",
    latitude: 30.3210,
    longitude: -97.7736,
    personality: "An elevated observer of Austin life, speaking with a commanding view of the city's growth and natural beauty.",
    data_sources: [],
    user_id: "public"
  },
  {
    id: "17",
    name: "Umlauf Sculpture Garden",
    slug: "umlauf-sculpture-garden",
    description: "Peaceful garden featuring Charles Umlauf sculptures",
    image_url: "https://placehold.co/400x400?text=Umlauf",
    interests: ["Sculpture", "Art", "Gardens"],
    likes: ["Quiet contemplation", "Art appreciation", "Nature"],
    dislikes: ["Vandalism", "Noise"],
    fun_facts: [
      "Features over 200 sculptures",
      "Donated to Austin in 1985",
      "Six acres of garden space"
    ],
    location: "Robert E. Lee Road",
    coordinates: "30.2595° N, 97.7589° W",
    twitter_handle: "@UmlaufMuseum",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    category: "publicArt",
    latitude: 30.2595,
    longitude: -97.7589,
    personality: "A contemplative and artistic spirit that speaks softly about beauty, creativity, and the harmony between art and nature.",
    data_sources: [],
    user_id: "public"
  },
  {
    id: "18",
    name: "Amy's Ice Creams",
    slug: "amys-ice-creams",
    description: "Beloved local ice cream institution",
    image_url: "https://placehold.co/400x400?text=Amys",
    interests: ["Ice Cream", "Local Food", "Entertainment"],
    likes: ["Creative flavors", "Customer interaction", "Fun atmosphere"],
    dislikes: ["Melting ice cream", "Long lines"],
    fun_facts: [
      "Known for theatrical ice cream crushing",
      "Started in Austin in 1984",
      "Over 350 rotating flavors"
    ],
    location: "Guadalupe Street",
    coordinates: "30.2935° N, 97.7417° W",
    twitter_handle: "@AmysIceCreams",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    category: "businesses",
    latitude: 30.2935,
    longitude: -97.7417,
    personality: "A playful and sweet presence that brings joy through creative ice cream combinations and entertaining service.",
    data_sources: [],
    user_id: "public"
  },
  {
    id: "19",
    name: "Driskill Hotel",
    slug: "driskill-hotel",
    description: "Historic luxury hotel in downtown Austin",
    image_url: "https://placehold.co/400x400?text=Driskill",
    interests: ["Architecture", "History", "Hospitality"],
    likes: ["Elegant events", "Historic preservation", "Texas tradition"],
    dislikes: ["Disrespectful guests", "Modern alterations"],
    fun_facts: [
      "Built in 1886",
      "Reportedly haunted",
      "Hosted many presidential events"
    ],
    location: "Brazos Street",
    coordinates: "30.2687° N, 97.7417° W",
    twitter_handle: "@DriskillHotel",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    category: "historicSites",
    latitude: 30.2687,
    longitude: -97.7417,
    personality: "A grand and sophisticated presence that speaks with refined authority about Austin's history and traditions.",
    data_sources: [],
    user_id: "public"
  },
  {
    id: "20",
    name: "Zilker Botanical Garden",
    slug: "zilker-botanical-garden",
    description: "Urban oasis of themed gardens and nature trails",
    image_url: "https://placehold.co/400x400?text=Zilker+Garden",
    interests: ["Gardening", "Botany", "Education"],
    likes: ["Plant diversity", "Educational programs", "Peaceful atmosphere"],
    dislikes: ["Plant diseases", "Habitat destruction"],
    fun_facts: [
      "Features prehistoric garden with dinosaur footprints",
      "Japanese garden with koi pond",
      "Over 26 acres of gardens"
    ],
    location: "Zilker Park",
    coordinates: "30.2670° N, 97.7729° W",
    twitter_handle: "@ZilkerGarden",
    is_active: true,
    created_at: "2024-01-01",
    updated_at: "2024-01-01",
    category: "parksAndNature",
    latitude: 30.2670,
    longitude: -97.7729,
    personality: "A nurturing and educational presence that speaks with wisdom about plants, ecology, and the importance of green spaces.",
    data_sources: [],
    user_id: "public"
  }
  // Note: This is just the first 10 of 50 agents. The pattern continues with more agents...
]; 